version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      - find $CODEBUILD_SRC_DIR/node_modules -exec touch {} +

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade pip
      - pip install --upgrade awscli

      # install dependencies required for CYPRESS testing
      - apt-get -q update && apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      # Use AWS SAM to package the application using AWS CloudFormation
      - mv reminders.js build
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
