version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      - find $CODEBUILD_SRC_DIR/node_modules -exec touch {} +
  build:
    commands:
      - npm run build
      # Use AWS SAM to package the application using AWS CloudFormation
      - mv template* build
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
